---
- name: Update package for Operative System
  ansible.builtin.include_tasks:
    file: linux-update-package.yml

- name: Linux prerequisites for OS System
  ansible.builtin.include_tasks: linux-prerequisites.yml

- name: Install packages to Operative System
  when: install_pkg is defined and install_pkg
  block:
    - name: Install generic package in redhat/debian/sles
      ansible.builtin.package:
        name: "{{ packages.common }}"
        state: present
      notify: restart_atd

    - name: Instalar software de Red Hat/CentOS
      ansible.builtin.include_tasks:
        file: linux-redhat-software-installation.yml
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution != "Amazon"

    - name: Instalar software de Debian/Ubuntu
      ansible.builtin.include_tasks:
        file: linux-debian-software-installation.yml
      when: ansible_os_family == "Debian"

    - name: Instalar software de SUSE
      ansible.builtin.include_tasks:
        file: linux-suse-software-installation.yml
      when: ansible_os_family == 'SLES'

    - name: Instalar software de Amazon
      ansible.builtin.include_tasks:
        file: '{{ "linux-amazon-software-installation.yml" if ansible_distribution_major_version | int !=2 else linux-amazon2-software-installation.yml }}'
      when: ansible_distribution == 'Amazon'

- name: Post personalice optimization for Os System
  ansible.builtin.include_tasks:
    file: linux-personalice-post.yml
