---
- name: Install software essential in Suse <= 15
  when: ansible_distribution_major_version | int <= 15
  community.general.zypper:
    name: "{{ packages[ansible_os_family] }}"
    state: present
