---
- name: Remove Playbook subsonic
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Stopped subsonic service
      ansible.builtin.service:
        name: subsonic
        state: stopped
      failed_when: 1 == 2

    - name: Check the process in remote server
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ps -fea|grep subsonic-booter|grep -v grep|awk -F " " '{print $2}' | uniq
      register: subsonic_booter
      changed_when: false
      failed_when: 1 == 2
      args:
        executable: /bin/bash

    - name: Kill the process
      ansible.builtin.command:
        cmd: kill -s 9 {{ subsonic_booter.stdout }}
      changed_when: false

    - name: Remove the package
      ansible.builtin.apt:
        name: subsonic
        state: absent
      failed_when: false

    - name: Remove directory subsonic
      ansible.builtin.file:
        path: /var/subsonic/
        state: absent
