---
- name: Remove Playbook subsonic
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Stopped subsonic service
      ansible.builtin.service:
        name: subsonic
        state: stopped
      ignore_errors: true

    - name: Remove the package
      ansible.builtin.apt:
        name: subsonic
        state: absent
      ignore_errors: true

    - name: Remove directory subsonic
      ansible.builtin.file:
        path: /var/subsonic/
        state: absent
