---
- name: Desplegar scripts en servidor Master
  hosts: master
  become: true
  gather_facts: true
  tasks:
    - name: Practicando a fondo - rol
      ansible.builtin.include_role:
        name: deploy
