---
- name: Install bind - chroot in remote server
  hosts: all
  become: true
  gather_facts: true
  vars:
    domain: "labrhel.com"
  tasks:
    - name: Add role bind
      ansible.builtin.include_role:
        name: deploy
