---
- name: reload_firewall
  ansible.builtin.systemd:
    name: firewalld
    state: restarted

- name: restart_chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted

- name: restart_sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
# handlers file for linea-base
